import { IIngredient, IRecipeBlob, IRecipeComplete } from "./src/API/API.types";

export const testDataIngredients: IIngredient[] = [
  { id: 149, categoryId: 29, name: "aborre" },
  { id: 124, categoryId: 18, name: "amadine potatis" },
  { id: 79, categoryId: 0, name: "avokado" },
  { id: 80, categoryId: 0, name: "babyspenat" },
  { id: 117, categoryId: 15, name: "bandpasta" },
  { id: 179, categoryId: 37, name: "basmatiris" },
  { id: 110, categoryId: 8, name: "blomkålshuvud" },
  { id: 43, categoryId: 17, name: "bringa" },
  { id: 25, categoryId: 8, name: "broccoli" },
  { id: 81, categoryId: 0, name: "böngroddar" },
  { id: 158, categoryId: 33, name: "cashewnötter" },
  { id: 1, categoryId: 21, name: "champinjoner" },
  { id: 144, categoryId: 28, name: "citron" },
  { id: 77, categoryId: 0, name: "citronskal" },
  { id: 126, categoryId: 19, name: "cosmopolitansallad" },
  { id: 154, categoryId: 31, name: "crème fraiche" },
  { id: 82, categoryId: 0, name: "curry" },
  { id: 85, categoryId: 0, name: "dill" },
  { id: 53, categoryId: 6, name: "dragon" },
  { id: 121, categoryId: 17, name: "entrecote" },
  { id: 146, categoryId: 29, name: "fisk" },
  { id: 132, categoryId: 23, name: "fiskbuljong" },
  { id: 108, categoryId: 1, name: "fiskbuljongtärning" },
  { id: 120, categoryId: 16, name: "fläsk" },
  { id: 38, categoryId: 16, name: "fläskfilé" },
  { id: 2, categoryId: 3, name: "fläskfärs" },
  { id: 12, categoryId: 16, name: "fläskkarre" },
  { id: 73, categoryId: 16, name: "fläskkotlett" },
  { id: 8, categoryId: 15, name: "fussili" },
  { id: 42, categoryId: 7, name: "färsk koriander" },
  { id: 83, categoryId: 0, name: "grillad paprika" },
  { id: 185, categoryId: 38, name: "gräddost" },
  { id: 84, categoryId: 0, name: "gräslök" },
  { id: 171, categoryId: 35, name: "grön paprika" },
  { id: 166, categoryId: 34, name: "gröna oliver" },
  { id: 133, categoryId: 23, name: "grönsaksbuljong" },
  { id: 72, categoryId: 1, name: "grönsaksbuljongtärning" },
  { id: 50, categoryId: 9, name: "gul lök" },
  { id: 169, categoryId: 35, name: "gul paprika" },
  { id: 76, categoryId: 0, name: "gurka" },
  { id: 150, categoryId: 29, name: "gös" },
  { id: 160, categoryId: 33, name: "hasselnötter" },
  { id: 55, categoryId: 11, name: "havre mjök" },
  { id: 86, categoryId: 0, name: "hickory glaze" },
  { id: 255, categoryId: 3, name: "hjortfärs" },
  { id: 127, categoryId: 19, name: "hjärtsallad" },
  { id: 251, categoryId: 29, name: "hälleflundra" },
  { id: 56, categoryId: 17, name: "högrev" },
  { id: 87, categoryId: 0, name: "ingefära" },
  { id: 17, categoryId: 20, name: "japansk soja" },
  { id: 180, categoryId: 37, name: "jasminris" },
  { id: 88, categoryId: 0, name: "jordnötssmör" },
  { id: 159, categoryId: 33, name: "jordnötter" },
  { id: 13, categoryId: 18, name: "jordärtskocka" },
  { id: 174, categoryId: 36, name: "kalkonfilé" },
  { id: 21, categoryId: 3, name: "kalkonfärs" },
  { id: 130, categoryId: 21, name: "kantareller" },
  { id: 137, categoryId: 24, name: "kikärter" },
  { id: 35, categoryId: 20, name: "kinesisk soja" },
  { id: 89, categoryId: 0, name: "kokosmjölk" },
  { id: 139, categoryId: 25, name: "kokta bruna bönor" },
  { id: 138, categoryId: 25, name: "kokta svarta bönor" },
  { id: 140, categoryId: 25, name: "kokta vita bönor" },
  { id: 3, categoryId: 5, name: "konc kalvfond" },
  { id: 4, categoryId: 5, name: "konc kycklingfond" },
  { id: 90, categoryId: 0, name: "koriander" },
  { id: 119, categoryId: 16, name: "kotletter" },
  { id: 91, categoryId: 0, name: "kronärtskockscrème" },
  { id: 33, categoryId: 41, name: "krossade tomater" },
  { id: 187, categoryId: 39, name: "kräftstjärt" },
  { id: 177, categoryId: 36, name: "kyckling" },
  { id: 135, categoryId: 23, name: "kycklingbuljong" },
  { id: 27, categoryId: 1, name: "kycklingbuljongtärning" },
  { id: 176, categoryId: 36, name: "kycklingfilé" },
  { id: 24, categoryId: 3, name: "kycklingfärs" },
  { id: 175, categoryId: 36, name: "kycklinglårfilé" },
  { id: 75, categoryId: 18, name: "kålrot" },
  { id: 189, categoryId: 40, name: "körsbärstomater" },
  { id: 134, categoryId: 23, name: "köttbuljong" },
  { id: 28, categoryId: 1, name: "köttbuljongtärning" },
  { id: 109, categoryId: 3, name: "köttfärs" },
  { id: 60, categoryId: 0, name: "lagerblad" },
  { id: 92, categoryId: 0, name: "lasagneplattor" },
  { id: 147, categoryId: 29, name: "laxfilé" },
  { id: 145, categoryId: 28, name: "lime" },
  { id: 118, categoryId: 15, name: "linguini" },
  { id: 93, categoryId: 0, name: "lufttorkad skinka" },
  { id: 94, categoryId: 0, name: "majonnäs" },
  { id: 95, categoryId: 0, name: "majskorn" },
  { id: 34, categoryId: 0, name: "majsstärkelse" },
  { id: 9, categoryId: 15, name: "makaroner" },
  { id: 96, categoryId: 0, name: "mandelsplitter (à 50g)" },
  { id: 161, categoryId: 33, name: "mandlar" },
  { id: 74, categoryId: 0, name: "matlagningsgrädde" },
  { id: 181, categoryId: 37, name: "matris" },
  { id: 156, categoryId: 32, name: "matyoghurt" },
  { id: 111, categoryId: 12, name: "mjöl" },
  { id: 7, categoryId: 11, name: "mjölk" },
  { id: 14, categoryId: 18, name: "morot" },
  { id: 128, categoryId: 19, name: "mâchesallad" },
  { id: 44, categoryId: 14, name: "neutral olja" },
  { id: 113, categoryId: 13, name: "nudlar" },
  { id: 64, categoryId: 3, name: "nötfärs" },
  { id: 123, categoryId: 17, name: "nötkött" },
  { id: 40, categoryId: 17, name: "nötrulle" },
  { id: 167, categoryId: 34, name: "oliver" },
  { id: 37, categoryId: 0, name: "olivolja" },
  { id: 114, categoryId: 14, name: "olja" },
  { id: 170, categoryId: 35, name: "orange paprika" },
  { id: 5, categoryId: 6, name: "oregano" },
  { id: 29, categoryId: 0, name: "ostronsås" },
  { id: 122, categoryId: 17, name: "oxfile" },
  { id: 49, categoryId: 8, name: "pak choi" },
  { id: 32, categoryId: 18, name: "palsternacka" },
  { id: 10, categoryId: 15, name: "papardelle" },
  { id: 173, categoryId: 35, name: "paprika" },
  { id: 97, categoryId: 0, name: "paprikapulver" },
  { id: 192, categoryId: 41, name: "passerade tomater" },
  { id: 115, categoryId: 15, name: "pasta" },
  { id: 39, categoryId: 15, name: "penne" },
  { id: 190, categoryId: 40, name: "plommontomater" },
  { id: 15, categoryId: 18, name: "potatis" },
  { id: 152, categoryId: 30, name: "pumpakärnor" },
  { id: 20, categoryId: 3, name: "quorn" },
  { id: 51, categoryId: 13, name: "ramen nudlar" },
  { id: 68, categoryId: 14, name: "rapsolja" },
  { id: 254, categoryId: 3, name: "renfärs" },
  { id: 178, categoryId: 37, name: "ris" },
  { id: 112, categoryId: 13, name: "risnudlar" },
  { id: 98, categoryId: 0, name: "rispapper" },
  { id: 182, categoryId: 38, name: "riven ost" },
  { id: 99, categoryId: 0, name: "riven pepparrot" },
  { id: 183, categoryId: 38, name: "riven prästost" },
  { id: 191, categoryId: 40, name: "romanticatomater" },
  { id: 125, categoryId: 18, name: "rotfrukt" },
  { id: 16, categoryId: 18, name: "rotselleri" },
  { id: 48, categoryId: 19, name: "rucola" },
  { id: 186, categoryId: 39, name: "räkor i lake" },
  { id: 26, categoryId: 12, name: "rågmjöl" },
  { id: 30, categoryId: 9, name: "röd lök" },
  { id: 168, categoryId: 35, name: "röd paprika" },
  { id: 141, categoryId: 26, name: "röd peppar (chili)" },
  { id: 172, categoryId: 35, name: "röd spetspaprika" },
  { id: 45, categoryId: 18, name: "rödbeta" },
  { id: 22, categoryId: 0, name: "rödvin" },
  { id: 200, categoryId: 43, name: "rödvinsvinäger" },
  { id: 58, categoryId: 0, name: "rökt sidfläsk" },
  { id: 129, categoryId: 19, name: "sallad" },
  { id: 78, categoryId: 0, name: "salladslök" },
  { id: 59, categoryId: 0, name: "salt" },
  { id: 142, categoryId: 27, name: "sambal öelek" },
  { id: 66, categoryId: 10, name: "schalottenlökar" },
  { id: 148, categoryId: 29, name: "sejfilé" },
  { id: 100, categoryId: 0, name: "senap" },
  { id: 101, categoryId: 0, name: "sesamfrön" },
  { id: 52, categoryId: 0, name: "sesamolja" },
  { id: 6, categoryId: 9, name: "silver lök" },
  { id: 31, categoryId: 0, name: "smör" },
  { id: 18, categoryId: 20, name: "soja" },
  { id: 136, categoryId: 24, name: "sojabönor" },
  { id: 153, categoryId: 30, name: "solrosfrön" },
  { id: 67, categoryId: 11, name: "soya mjölk" },
  { id: 11, categoryId: 15, name: "spaghetti" },
  { id: 102, categoryId: 0, name: "spiskummin" },
  { id: 143, categoryId: 27, name: "sriracha" },
  { id: 54, categoryId: 10, name: "steklökar" },
  { id: 19, categoryId: 0, name: "ströbröd" },
  { id: 46, categoryId: 22, name: "strösocker" },
  { id: 131, categoryId: 21, name: "svamp" },
  { id: 165, categoryId: 34, name: "svarta oliver" },
  { id: 36, categoryId: 0, name: "svartpeppar" },
  { id: 103, categoryId: 0, name: "sweet chilisås" },
  { id: 184, categoryId: 38, name: "taco ost" },
  { id: 104, categoryId: 0, name: "teriyakimarinad" },
  { id: 65, categoryId: 7, name: "timjan" },
  { id: 105, categoryId: 0, name: "tofu" },
  { id: 188, categoryId: 40, name: "tomat" },
  { id: 193, categoryId: 41, name: "tomatburk" },
  { id: 41, categoryId: 0, name: "tomatpuré" },
  { id: 199, categoryId: 42, name: "torkade beluga linser" },
  { id: 198, categoryId: 42, name: "torkade bruna linser" },
  { id: 197, categoryId: 42, name: "torkade gröna linser" },
  { id: 196, categoryId: 42, name: "torkade gula linser" },
  { id: 194, categoryId: 42, name: "torkade röda linser" },
  { id: 195, categoryId: 42, name: "torkade svarta linser" },
  { id: 151, categoryId: 29, name: "torsk" },
  { id: 116, categoryId: 15, name: "trottole" },
  { id: 164, categoryId: 34, name: "urkärnade gröna oliver" },
  { id: 163, categoryId: 34, name: "urkärnade svarta oliver" },
  { id: 162, categoryId: 33, name: "valnötter" },
  { id: 61, categoryId: 0, name: "vatten" },
  { id: 155, categoryId: 31, name: "vegansk fraiche" },
  { id: 47, categoryId: 12, name: "vetemjöl" },
  { id: 69, categoryId: 13, name: "vetenudlar" },
  { id: 253, categoryId: 3, name: "viltfärs" },
  { id: 71, categoryId: 0, name: "vispgrädde" },
  { id: 62, categoryId: 8, name: "vitkål" },
  { id: 63, categoryId: 0, name: "vitlöksklyfta" },
  { id: 201, categoryId: 43, name: "vitvinsvinäger" },
  { id: 157, categoryId: 32, name: "växtbaserad fraiche" },
  { id: 106, categoryId: 0, name: "zucchini" },
  { id: 23, categoryId: 0, name: "ägg" },
  { id: 70, categoryId: 13, name: "äggnudlar" },
  { id: 252, categoryId: 3, name: "älgfärs" },
  { id: 202, categoryId: 43, name: "äppelcidervinäger" },
  { id: 107, categoryId: 0, name: "ättiksprit 12%" },
];

export const testDataRecipe: IRecipeComplete = {
  recipe: {
    id: 2,
    name: "Boeuf Bourgnioun med potatismos",
    description:
      "Description Från Arla - Sugen på något värmande? Laga boeuf bourguignon, även kallad burgundisk köttgryta, som värmer både kropp och själ! Den mustiga grytan med högrev, rött vin, sidfläsk, lök, champinjon och morot serveras med krämigt pot...",
    imgLink:
      "https://images.unsplash.com/photo-1608500218882-986df81d55fc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80",
    portions: 6,
    cookingTime: 60,
  },
  recipeSteps: [
    {
      row: 1,
      text: "Skär köttet i ca 5x5 cm stora bitar. Skär sidfläsket i små tärningar. Skala schalottenlök, vitlök och morötter. Skär schalottenlök och morötter i stora bitar. Skiva vitlöken.\n",
    },
    {
      row: 2,
      text: "Fräs schalottenlök, vitlök, morötter, hälften av fläsket och tomatpurén i en stor gryta i hälften av smöret tills löken mjuknar.",
    },
    {
      row: 3,
      text: "Bryn köttet i resten av smöret i en stor stekpanna tills det får färg runtom. Tillsätt vattnet, låt koka någon minut och häll ner i grytan med grönsaksfräset. Pudra över mjöl och rör om. Tillsätt vin, fond, soja, timjan och lagerblad.",
    },
    {
      row: 4,
      text: "Låt koka upp och skumma av. Sjud på svag värme med locket på glänt ca 1 ½–2 timmar tills köttet är mört.",
    },
    {
      row: 5,
      text: "Potatismos: Skala och koka potatisen mjuk i lättsaltat vatten. Häll av och ånga av. Fräs vitlöken i smöret. Häll i grädde och mjölk och låt koka upp. Pressa potatisen och vispa ihop med lökgrädden. Tillsätt citronskal och smaka av med salt.",
    },
    {
      row: 6,
      text: "Svampfräs: Skala steklöken och halvera om de är stora. Ansa och halvera champinjonerna. Stek lök, champinjoner och resten av sidfläsket i smöret tills det får färg och löken är mjuk.",
    },
    {
      row: 7,
      text: "Smaka av grytan med salt och peppar. Toppa med svampfräset och servera med potatismoset.\n",
    },
  ],
  recipeIngredient: [
    {
      ingredientId: 1,
      quantity: 400,
      measurement: "g",
      originalIngredient: "champinjoner",
    },
    {
      ingredientId: 56,
      quantity: 1,
      measurement: "kg",
      originalIngredient: "högrev",
    },
    {
      ingredientId: 3,
      quantity: 2,
      measurement: "msk",
      originalIngredient: "konc kalvfond",
    },
    {
      ingredientId: 60,
      quantity: 3,
      measurement: "st",
      originalIngredient: "lagerblad",
    },
    {
      ingredientId: 7,
      quantity: 2,
      measurement: "dl",
      originalIngredient: "mjölk",
    },
    {
      ingredientId: 14,
      quantity: 3,
      measurement: "st",
      originalIngredient: "morot",
    },
    {
      ingredientId: 15,
      quantity: 1,
      measurement: "kg",
      originalIngredient: "potatis",
    },
    {
      ingredientId: 22,
      quantity: 5,
      measurement: "dl",
      originalIngredient: "rödvin",
    },
    {
      ingredientId: 58,
      quantity: 200,
      measurement: "g",
      originalIngredient: "rökt sidfläsk",
    },
    {
      ingredientId: 59,
      quantity: 0,
      measurement: null,
      originalIngredient: "salt",
    },
    {
      ingredientId: 66,
      quantity: 2,
      measurement: "st",
      originalIngredient: "schalottenlökar",
    },
    {
      ingredientId: 31,
      quantity: 4,
      measurement: "msk",
      originalIngredient: "smör",
    },
    {
      ingredientId: 31,
      quantity: 25,
      measurement: "g",
      originalIngredient: "smör",
    },
    {
      ingredientId: 31,
      quantity: 2,
      measurement: "msk",
      originalIngredient: "smör",
    },
    {
      ingredientId: 18,
      quantity: 1,
      measurement: "msk",
      originalIngredient: "soja",
    },
    {
      ingredientId: 54,
      quantity: 250,
      measurement: "g",
      originalIngredient: "steklökar",
    },
    {
      ingredientId: 36,
      quantity: 0,
      measurement: null,
      originalIngredient: "svartpeppar",
    },
    {
      ingredientId: 65,
      quantity: 1,
      measurement: "tsk",
      originalIngredient: "timjan",
    },
    {
      ingredientId: 41,
      quantity: 1,
      measurement: "msk",
      originalIngredient: "tomatpuré",
    },
    {
      ingredientId: 61,
      quantity: 1,
      measurement: "dl",
      originalIngredient: "vatten",
    },
    {
      ingredientId: 47,
      quantity: 2,
      measurement: "msk",
      originalIngredient: "vetemjöl",
    },
    {
      ingredientId: 71,
      quantity: 1,
      measurement: "dl",
      originalIngredient: "vispgrädde",
    },
    {
      ingredientId: 63,
      quantity: 1,
      measurement: "st",
      originalIngredient: "vitlöksklyfta",
    },
    {
      ingredientId: 63,
      quantity: 3,
      measurement: "st",
      originalIngredient: "vitlöksklyfta",
    },
  ],
  ingredientConverter: [
    {
      categoryId: 12,
      ingredientId: 47,
      originalIngredient: "vetemjöl",
      replacementIngredient: "rågmjöl",
    },
  ],
};

export const testDataRecipeMatches: IRecipeBlob[] = [
  {
    matches: 3,
    id: 2,
    name: "Boeuf Bourgnioun med potatismos",
    description:
      "Description Från Arla - Sugen på något värmande? Laga boeuf bourguignon, även kallad burgundisk köttgryta, som värmer både kropp och själ! Den mustiga grytan med högrev, rött vin, sidfläsk, lök, champinjon och morot serveras med krämigt pot...",
    imgLink:
      "https://images.unsplash.com/photo-1608500218882-986df81d55fc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80",
    portions: 6,
    cookingTime: 60,
  },
  {
    matches: 1,
    id: 15,
    name: "Potatiskakor med kantareller och pepparrotskräm",
    description:
      "Den mångsidiga potatisen här i form av vegetariska biffar som smaksätts med senapsvinägrett och rödlök och äts tillsammans med stekta kantareller, pepparrotskräm och inlagd gurka med smak av dill.",
    imgLink:
      "https://via.placeholder.com/800/FD7463/FFFFFF/?text=Picture%20Coming%20Soon",
    portions: 4,
    cookingTime: 60,
  },
  {
    matches: 1,
    id: 10,
    name: "Kalkonfärslasagne med hjärtsallad",
    description:
      "Lasagne gjord på kalkonfärs är en riktig höjdare. Också en perfekt rätt att laga någon dag innan den ska ätas, om du skulle ha bråttom en annan dag. Också perfekt att frysa in om det blir över.",
    imgLink:
      "https://images.unsplash.com/photo-1619895092538-128341789043?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    portions: 4,
    cookingTime: 45,
  },
  {
    matches: 1,
    id: 4,
    name: "Wok med äggnudlar och fläskfilé",
    description:
      "Description Från Arla - Fräscha grönsaker med salt, rökt fläsk eller skinka är jättegott tillsammans. Du behöver ingen wok för att lyckas med denna rätt, det går bra med en stor stekpanna.",
    imgLink:
      "https://cdn.pixabay.com/photo/2020/08/05/18/55/meal-5466163_960_720.jpg",
    portions: 4,
    cookingTime: 30,
  },
  {
    matches: 1,
    id: 3,
    name: "Kycklingbullar i dragonsås",
    description:
      "Description från ICA - Köttbullar gjorda på kycklingfärs med smak av dragon, citron och dijonsenap.",
    imgLink:
      "https://images.unsplash.com/photo-1584949602318-398849a6ea4e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=987&q=80",
    portions: 8,
    cookingTime: 45,
  },
  {
    matches: 1,
    id: 1,
    name: "Spaghetti Bolognese",
    description:
      "Description Från Arla - Gör en extra stor sats av allas vardagsfavorit, spagetti och köttfärssås, och frys in. Vill du variera smaken, prova med lamm- eller viltfärs istället för nötfärs!",
    imgLink:
      "https://images.unsplash.com/photo-1598866594230-a7c12756260f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
    portions: 4,
    cookingTime: 30,
  },
];
